<?php
if($_SESSION['lang']=="en"){
    define('SHOP_ADMIN_MOD_NAME','Shop');
    
    define('SHOP_ADMIN_NOTE_SAVED','Saved!');
    define('SHOP_ADMIN_NOTE_EDITOR_CAT','Edit category');
    define('SHOP_ADMIN_NOTE_EDITOR','Edit article');
    define('SHOP_ADMIN_NOTE_EDIT','Edit');
    define('SHOP_ADMIN_NOTE_CAPTION','Caption');
    define('SHOP_ADMIN_NOTE_IMAGE','Picture');
    define('SHOP_ADMIN_NOTE_IMAGE_SIZE','Size');
    define('SHOP_ADMIN_NOTE_ATTANTION_IMAGE_SIZE','Very large size!');
    define('SHOP_ADMIN_NOTE_EDIT_IMAGE','Edit picture');
    define('SHOP_ADMIN_NOTE_CATEGORY','Category');
    define('SHOP_ADMIN_NOTE_SELECT_CATEGORY','Select a category');
    define('SHOP_ADMIN_NOTE_SHORT_DESCRIPTION','Short description');
    define('SHOP_ADMIN_NOTE_FULL_DESCRIPTION','Full description');
    define('SHOP_ADMIN_NOTE_SHOW','Show');
    define('SHOP_ADMIN_NOTE_SHOW_ONLINE','Show Online');
    define('SHOP_ADMIN_NOTE_SHOW_ALL','Show all');
    define('SHOP_ADMIN_NOTE_ATTANTION_DELETE','Are you sure you want to delete the record');
    define('SHOP_ADMIN_NOTE_MAIN_SECTION','Main section');
    define('SHOP_ADMIN_NOTE_SECTION','Section');
    define('SHOP_ADMIN_NOTE_TAG_SECTION','Tag-section');
    define('SHOP_ADMIN_NOTE_MENU_CATEGORY','Category menu');
    define('SHOP_ADMIN_NOTE_OPTIONS','Options');
    define('SHOP_ADMIN_NOTE_OPEN','Open');
    define('SHOP_ADMIN_NOTE_PRICE','Price');
    define('SHOP_ADMIN_NOTE_SHOP_PRICE','Shop price');
    define('SHOP_ADMIN_NOTE_SHOP_CODE','Code');
    define('SHOP_ADMIN_NOTE_SHOP_CODE_ATTANTION','Introduced without taking into account parameters');
    define('SHOP_ADMIN_NOTE_AVAILABILITY','Availability');
    define('SHOP_ADMIN_NOTE_ITEM_CARD','Card product');
    define('SHOP_ADMIN_NOTE_GOOD_PRICE_SALE','Good price, sale');
    define('SHOP_ADMIN_NOTE_GOOD_PRICE','Good price');
    define('SHOP_ADMIN_NOTE_SALE','Sale');
    define('SHOP_ADMIN_NOTE_ON_MAIN','On home page');
    define('SHOP_ADMIN_NOTE_CHARACTERISTIC','Characteristics');
    define('SHOP_ADMIN_NOTE_COURSE','Exchange Rates');
    define('SHOP_ADMIN_NOTE_FLAGSHIP','Flagship');
    define('SHOP_ADMIN_NOTE_PARAMETERS','Parameters');
    define('SHOP_ADMIN_NOTE_PARAMETERS_ATTENTION','Select parameter');
    define('SHOP_ADMIN_NOTE_BRANCH','Branches of application');
    define('SHOP_ADMIN_NOTE_PHOTO_APPLICATION','Photo of application');
    define('SHOP_ADMIN_NOTE_RELATED_PRODUCT','Options');
    define('SHOP_ADMIN_NOTE_OVERVIEW_PRODUCTS','Products Overview');
    define('SHOP_ADMIN_NOTE_PRESENT','Present');
    define('SHOP_ADMIN_NOTE_FILTER','Filters');
        
    define('SHOP_ADMIN_BUTTON_BACK','Back');
    define('SHOP_ADMIN_BUTTON_ADD_NEW','Add new record');
    define('SHOP_ADMIN_BUTTON_VIEW_ONLINE','View online');
    define('SHOP_ADMIN_BUTTON_SAVE','Save');
    define('SHOP_ADMIN_BUTTON_DELETE','Delete');
    define('SHOP_ADMIN_BUTTON_UP','Up');
    define('SHOP_ADMIN_BUTTON_DOWN','Down');
}
elseif($_SESSION['lang']=="ru"){
    define('SHOP_ADMIN_MOD_NAME','Магазин');
    
    define('SHOP_ADMIN_NOTE_SAVED','Данные сохранены!');
    define('SHOP_ADMIN_NOTE_EDITOR_CAT','Редактор категории');
    define('SHOP_ADMIN_NOTE_EDITOR','Редактор статьи'); 
    define('SHOP_ADMIN_NOTE_EDIT','Редактировать');
    define('SHOP_ADMIN_NOTE_CAPTION','Название');
    define('SHOP_ADMIN_NOTE_IMAGE','Изображение');
    define('SHOP_ADMIN_NOTE_IMAGE_SIZE','Размер');
    define('SHOP_ADMIN_NOTE_ATTANTION_IMAGE_SIZE','Очень большой размер!');
    define('SHOP_ADMIN_NOTE_EDIT_IMAGE','Редактировать изображение');
    define('SHOP_ADMIN_NOTE_CATEGORY','Категория');
    define('SHOP_ADMIN_NOTE_SELECT_CATEGORY','Выберите категорию'); 
    define('SHOP_ADMIN_NOTE_SHORT_DESCRIPTION','Краткое описание');
    define('SHOP_ADMIN_NOTE_FULL_DESCRIPTION','Текст статьи');
    define('SHOP_ADMIN_NOTE_SHOW','Видимость');
    define('SHOP_ADMIN_NOTE_SHOW_ONLINE','Показывать на сайте');
    define('SHOP_ADMIN_NOTE_SHOW_ALL','Показывать все');
    define('SHOP_ADMIN_NOTE_ATTANTION_DELETE','Вы уверены что хотите удалить запись');
    define('SHOP_ADMIN_NOTE_MAIN_SECTION','Главная секция');
    define('SHOP_ADMIN_NOTE_SECTION','Секция');
    define('SHOP_ADMIN_NOTE_TAG_SECTION','Тег-секция');
    define('SHOP_ADMIN_NOTE_MENU_CATEGORY','Меню категорий');
    define('SHOP_ADMIN_NOTE_OPTIONS','Опции');
    define('SHOP_ADMIN_NOTE_OPEN','Открыть');
    define('SHOP_ADMIN_NOTE_PRICE','Цена');
    define('SHOP_ADMIN_NOTE_SHOP_PRICE','Цена магазина');
    define('SHOP_ADMIN_NOTE_SHOP_CODE','Код');
    define('SHOP_ADMIN_NOTE_SHOP_CODE_ATTANTION','Вводится без учета параметров');
    define('SHOP_ADMIN_NOTE_AVAILABILITY','Наличие');
    define('SHOP_ADMIN_NOTE_ITEM_CARD','Карточка товара');
    define('SHOP_ADMIN_NOTE_GOOD_PRICE_SALE','Хорошая цена, распродажа');
    define('SHOP_ADMIN_NOTE_GOOD_PRICE','Хорошая цена');
    define('SHOP_ADMIN_NOTE_SALE','Распродажа');
    define('SHOP_ADMIN_NOTE_ON_MAIN','На главной');
    define('SHOP_ADMIN_NOTE_CHARACTERISTIC','Характеристики');
    define('SHOP_ADMIN_NOTE_COURSE','Курс');
    define('SHOP_ADMIN_NOTE_FLAGSHIP','Флагман');
    define('SHOP_ADMIN_NOTE_PARAMETERS','Параметри');
    define('SHOP_ADMIN_NOTE_PARAMETERS_ATTENTION','Выберите 2 параметра');
    define('SHOP_ADMIN_NOTE_BRANCH','Отрасли применения');
    define('SHOP_ADMIN_NOTE_PHOTO_APPLICATION','Фотографии применения');
    define('SHOP_ADMIN_NOTE_RELATED_PRODUCT','Опции');
    define('SHOP_ADMIN_NOTE_OVERVIEW_PRODUCTS','Обзор товаров');
    define('SHOP_ADMIN_NOTE_PRESENT','Подарок');
    define('SHOP_ADMIN_NOTE_FILTER','Фильтры');
    
    define('SHOP_ADMIN_BUTTON_BACK','Вернуться к списку записей');
    define('SHOP_ADMIN_BUTTON_ADD_NEW','Добавить новую запись');
    define('SHOP_ADMIN_BUTTON_VIEW_ONLINE','Посмотреть на сайте');
    define('SHOP_ADMIN_BUTTON_SAVE','Сохранить');
    define('SHOP_ADMIN_BUTTON_DELETE','Удалить');
    define('SHOP_ADMIN_BUTTON_UP','Вверх');
    define('SHOP_ADMIN_BUTTON_DOWN','Вниз');  
}else{
	define('SHOP_ADMIN_MOD_NAME','Магазин');
	
	define('SHOP_ADMIN_NOTE_SAVED','Дані збережені!');
	define('SHOP_ADMIN_NOTE_EDITOR_CAT','Редактор категорії');
	define('SHOP_ADMIN_NOTE_EDITOR','Редактор статті');
	define('SHOP_ADMIN_NOTE_EDIT','Редагувати');
	define('SHOP_ADMIN_NOTE_CAPTION','Назва');
	define('SHOP_ADMIN_NOTE_IMAGE','Зображення');
	define('SHOP_ADMIN_NOTE_IMAGE_SIZE','Розмір');
	define('SHOP_ADMIN_NOTE_ATTANTION_IMAGE_SIZE','Дуже великий розмір!');
	define('SHOP_ADMIN_NOTE_EDIT_IMAGE','Редагувати зображення');
	define('SHOP_ADMIN_NOTE_CATEGORY','Категорія');
	define('SHOP_ADMIN_NOTE_SELECT_CATEGORY','Оберіть категорію');
	define('SHOP_ADMIN_NOTE_SHORT_DESCRIPTION','Короткий опис');
	define('SHOP_ADMIN_NOTE_FULL_DESCRIPTION','Текст статті');
	define('SHOP_ADMIN_NOTE_SHOW','Видимість');
	define('SHOP_ADMIN_NOTE_SHOW_ONLINE','Показувати на сайті');
	define('SHOP_ADMIN_NOTE_SHOW_ALL','Показувати все');
	define('SHOP_ADMIN_NOTE_ATTANTION_DELETE','Ви впевнені що хочете видалити запис');
	define('SHOP_ADMIN_NOTE_MAIN_SECTION','Головна секція');
	define('SHOP_ADMIN_NOTE_SECTION','Секція');
	define('SHOP_ADMIN_NOTE_TAG_SECTION','Тег-секція');
	define('SHOP_ADMIN_NOTE_MENU_CATEGORY','Меню категорій');
	define('SHOP_ADMIN_NOTE_OPTIONS','Опції');
	define('SHOP_ADMIN_NOTE_OPEN','Відкрити');
	define('SHOP_ADMIN_NOTE_PRICE','Ціна');
	define('SHOP_ADMIN_NOTE_SHOP_PRICE','Ціна магазину');
	define('SHOP_ADMIN_NOTE_SHOP_CODE','Код');
	define('SHOP_ADMIN_NOTE_SHOP_CODE_ATTANTION','Вводиться без урахування параметрів');
	define('SHOP_ADMIN_NOTE_AVAILABILITY','Наявність');
	define('SHOP_ADMIN_NOTE_ITEM_CARD','Картка товару');
	define('SHOP_ADMIN_NOTE_GOOD_PRICE_SALE','Хороша ціна, розпродаж');
	define('SHOP_ADMIN_NOTE_GOOD_PRICE','Хороша ціна');
	define('SHOP_ADMIN_NOTE_SALE','Розпродаж');
	define('SHOP_ADMIN_NOTE_ON_MAIN','На головній');
	define('SHOP_ADMIN_NOTE_CHARACTERISTIC','Характеристики');
	define('SHOP_ADMIN_NOTE_COURSE','Курс');
	define('SHOP_ADMIN_NOTE_FLAGSHIP','Флагман');
	define('SHOP_ADMIN_NOTE_PARAMETERS','Параметри');
	define('SHOP_ADMIN_NOTE_PARAMETERS_ATTENTION','Виберіть 2 параметра');
	define('SHOP_ADMIN_NOTE_BRANCH','Галузі застосування');
	define('SHOP_ADMIN_NOTE_PHOTO_APPLICATION','Фотографії застосування');
	define('SHOP_ADMIN_NOTE_RELATED_PRODUCT','Опції');
	define('SHOP_ADMIN_NOTE_OVERVIEW_PRODUCTS','Огляд товарів');
	define('SHOP_ADMIN_NOTE_PRESENT','Подарунок');
	define('SHOP_ADMIN_NOTE_FILTER','Фільтри');
	
	define('SHOP_ADMIN_BUTTON_BACK','Назад до списку записів');
	define('SHOP_ADMIN_BUTTON_ADD_NEW','Додати новий запис');
	define('SHOP_ADMIN_BUTTON_VIEW_ONLINE','Подивитися на сайті');
	define('SHOP_ADMIN_BUTTON_SAVE','Зберегти');
	define('SHOP_ADMIN_BUTTON_DELETE','Видалити');
	define('SHOP_ADMIN_BUTTON_UP','Вгору');
    define('SHOP_ADMIN_BUTTON_DOWN','Вниз');
}
?>
